name: Deploy to e9cipher.github.io

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout React repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install
        working-directory: ./YOUR_FOLDER

      - name: Build project
        run: npm run build
        working-directory: ./YOUR_FOLDER

      - name: Deploy to GitHub Pages repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${{ secrets.GH_PAGES_DEPLOY }}@github.com/e9cipher/e9cipher.github.io.git output

          rm -rf output/*
          cp -r YOUR_FOLDER/build/* output/

          cd output
          git add .
          git commit -m "Deploy from React app" || echo "No changes"
          git push
